### ISSUE TITLE
Recaptcha issue is blocking submission

### ISSUE THREAD

**Issue by tatimblin** [maoberlehner/building-a-serverless-comment-system-with-netlify-functions-storyblok-and-vue#1]
I've been following along to this repo's associated blog, and ran into an error when adding comments to Storyblok.

Looks like something with the recaptcha is failing locally and on your [Netlify demo](https://serverless-comment-system.netlify.com/). Could you look into what's not working with your recaptcha account or how to remove the recaptcha feature entirely? Simply undoing everything in the blog recaptcha section did not work for me.

Thanks

**Comment by maoberlehner** [comment]
Hey @tatimblin,

I've just successfully added a new comment on the demo page. I guess you're detected as a bot for some reason?!

If you checkout this commit: https://github.com/maoberlehner/building-a-serverless-comment-system-with-netlify-functions-storyblok-and-vue/commit/4ba453335420829e1638178d7a260e7879ed3964 everything should work without the captcha. But I don't recommend running it without a captcha!

**Comment by tatimblin** [comment]
Thanks for your quick response! I've been messing with the commit you referenced the past few days, but still cannot get around the error (I am now able submit on the demo page by using Firefox).

See the error I'm talking about `Unhandled promise rejection Error: "Request failed with status code 500"`, by submitting a comment on the [repo](https://github.com/tatimblin/comment-system-with-netlify-functions-storyblok-and-vue) I copied from the 4ba4533 commit, and hosted no [netlify](https://jamstack-comment.netlify.com/). Let me know any insights you might have into this.

I also realize that this was a quick experiment for you, and you might not want to spend time with peoples issues. If there is any reference you'd rather point me to, that would be appreciated as well.
